// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQayfynUgAMUNlMhyXDNjpJB1P658OWv4',
    appId: '1:358834824544:web:9e706eccb2fa8f5cc52a05',
    messagingSenderId: '358834824544',
    projectId: 'recipes-d6ce7',
    authDomain: 'recipes-d6ce7.firebaseapp.com',
    databaseURL: 'https://recipes-d6ce7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipes-d6ce7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2NIWWSHiC1E4LXFaOzIx3ec7L-P-QCb0',
    appId: '1:358834824544:android:66c48f62b09b993fc52a05',
    messagingSenderId: '358834824544',
    projectId: 'recipes-d6ce7',
    databaseURL: 'https://recipes-d6ce7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipes-d6ce7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8MBXoqdSNkOpO772WNHPkKGyFGyZL4A4',
    appId: '1:358834824544:ios:5854b6675eecc532c52a05',
    messagingSenderId: '358834824544',
    projectId: 'recipes-d6ce7',
    databaseURL: 'https://recipes-d6ce7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipes-d6ce7.appspot.com',
    iosClientId: '358834824544-o1e57hidnnujpoh14l60k1nl8mbqjo0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.limoko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8MBXoqdSNkOpO772WNHPkKGyFGyZL4A4',
    appId: '1:358834824544:ios:a5b910d5b173403ac52a05',
    messagingSenderId: '358834824544',
    projectId: 'recipes-d6ce7',
    databaseURL: 'https://recipes-d6ce7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'recipes-d6ce7.appspot.com',
    iosClientId: '358834824544-2rc9hsqbsfrba83hvoo24s32gkoe4vsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.limoko.RunnerTests',
  );
}
